# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_jarvis_main_gui(object):
    def setupUi(self, jarvis_main_gui):
        jarvis_main_gui.setObjectName("jarvis_main_gui")
        jarvis_main_gui.resize(1200, 600)
        jarvis_main_gui.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Gopi_Tech = QtWidgets.QLabel(jarvis_main_gui)
        self.Gopi_Tech.setGeometry(QtCore.QRect(290, 20, 901, 71))
        self.Gopi_Tech.setText("")
        self.Gopi_Tech.setPixmap(QtGui.QPixmap("images\\gopi_tech.png"))
        self.Gopi_Tech.setScaledContents(True)
        self.Gopi_Tech.setObjectName("Gopi_Tech")
        self.coding_animation = QtWidgets.QLabel(jarvis_main_gui)
        self.coding_animation.setGeometry(QtCore.QRect(10, 10, 261, 111))
        self.coding_animation.setText("")
        self.coding_animation.setPixmap(QtGui.QPixmap("images\\upper_img.gif"))
        self.coding_animation.setScaledContents(True)
        self.coding_animation.setObjectName("coding_animation")
        self.Iron_Man_IMG = QtWidgets.QLabel(jarvis_main_gui)
        self.Iron_Man_IMG.setGeometry(QtCore.QRect(960, 100, 231, 491))
        self.Iron_Man_IMG.setText("")
        self.Iron_Man_IMG.setPixmap(QtGui.QPixmap("images\\center_img.gif"))
        self.Iron_Man_IMG.setScaledContents(True)
        self.Iron_Man_IMG.setObjectName("Iron_Man_IMG")
        self.Ar_Reactor = QtWidgets.QLabel(jarvis_main_gui)
        self.Ar_Reactor.setGeometry(QtCore.QRect(640, 110, 301, 211))
        self.Ar_Reactor.setText("")
        self.Ar_Reactor.setPixmap(QtGui.QPixmap("images\\sleeping_img.gif"))
        self.Ar_Reactor.setScaledContents(True)
        self.Ar_Reactor.setObjectName("Ar_Reactor")
        self.frame = QtWidgets.QFrame(jarvis_main_gui)
        self.frame.setGeometry(QtCore.QRect(10, 330, 941, 251))
        self.frame.setStyleSheet("color:rgb(255, 255, 255);\n"
                                 "border-color: rgb(255, 255, 255);\n"
                                 "border-radius:10px;\n"
                                 "border-style: solid;\n"
                                 "border-width: 5px 5px 5px 5px\n"
                                 "")
        # self.frame.setFrameShape(QtCore.Qt.QFrame::Shape::StyledPanel)
        # self.frame.setFrameShadow(QtCore.Qt.QFrame::Shadow::Raised)
        self.frame.setObjectName("frame")
        self.exit_Button = QtWidgets.QPushButton(self.frame)
        self.exit_Button.setGeometry(QtCore.QRect(840, 190, 91, 51))
        self.exit_Button.setStyleSheet("image: url(images/exit.png);")
        self.exit_Button.setText("")
        self.exit_Button.setObjectName("exit_Button")
        self.terminalinputBox = QtWidgets.QPlainTextEdit(self.frame)
        self.terminalinputBox.setGeometry(QtCore.QRect(0, 0, 941, 171))
        self.terminalinputBox.setStyleSheet("font: 800 11pt \"Rockwell Extra \";\n"
                                            "padding-left: 15px;")
        self.terminalinputBox.setBackgroundVisible(False)
        self.terminalinputBox.setObjectName("terminalinputBox")
        self.Text_enter = QtWidgets.QLineEdit(self.frame)
        self.Text_enter.setGeometry(QtCore.QRect(0, 190, 831, 41))
        self.Text_enter.setAutoFillBackground(False)

        self.Text_enter.setStyleSheet("font: 800 11pt \"Rockwell Extra Bold\";\n"
                                      "padding-left: 15px;\n"
                                      "")
        self.Text_enter.setText("")
        self.Text_enter.setObjectName("Text_enter")
        self.enter_Button = QtWidgets.QPushButton(self.frame)
        self.enter_Button.setGeometry(QtCore.QRect(730, 190, 101, 41))
        self.enter_Button.setStyleSheet("image: url(images/enter.png);")
        self.enter_Button.setText("")
        self.enter_Button.setObjectName("enter_Button")
        self.loading_label = QtWidgets.QLabel(jarvis_main_gui)
        self.loading_label.setGeometry(QtCore.QRect(20, 140, 261, 171))
        self.loading_label.setText("")
        self.loading_label.setPixmap(QtGui.QPixmap("images\\loading.gif"))
        self.loading_label.setScaledContents(True)
        self.loading_label.setObjectName("loading_label")
        self.listening_label = QtWidgets.QLabel(jarvis_main_gui)
        self.listening_label.setGeometry(QtCore.QRect(20, 140, 261, 171))
        self.listening_label.setText("")
        self.listening_label.setPixmap(QtGui.QPixmap("images\\listening.gif"))
        self.listening_label.setScaledContents(True)
        self.listening_label.setObjectName("listening_label")
        self.speaking_label = QtWidgets.QLabel(jarvis_main_gui)
        self.speaking_label.setGeometry(QtCore.QRect(20, 140, 261, 171))
        self.speaking_label.setText("")
        self.speaking_label.setPixmap(QtGui.QPixmap("images\\VAQa.gif"))
        self.speaking_label.setScaledContents(True)
        self.speaking_label.setObjectName("speaking_label")
        self.sleeping_label = QtWidgets.QLabel(jarvis_main_gui)
        self.sleeping_label.setGeometry(QtCore.QRect(20, 140, 261, 171))
        self.sleeping_label.setText("")
        self.sleeping_label.setPixmap(QtGui.QPixmap("images\\sleeping_img.gif"))
        self.sleeping_label.setScaledContents(True)
        self.sleeping_label.setObjectName("sleeping_label")
        self.Ar_Reactor_2 = QtWidgets.QLabel(jarvis_main_gui)
        self.Ar_Reactor_2.setGeometry(QtCore.QRect(310, 110, 301, 211))
        self.Ar_Reactor_2.setText("")
        self.Ar_Reactor_2.setPixmap(QtGui.QPixmap("images\\side_img.gif"))
        self.Ar_Reactor_2.setScaledContents(True)
        self.Ar_Reactor_2.setObjectName("Ar_Reactor_2")

        self.retranslateUi(jarvis_main_gui)
        QtCore.QMetaObject.connectSlotsByName(jarvis_main_gui)

    def retranslateUi(self, jarvis_main_gui):
        _translate = QtCore.QCoreApplication.translate
        jarvis_main_gui.setWindowTitle(_translate("jarvis_main_gui", "jarvis_main_gui"))
        self.terminalinputBox.setPlaceholderText(_translate("jarvis_main_gui", "Trminal input goes here..."))
        self.Text_enter.setPlaceholderText(_translate("jarvis_main_gui", "Enter You Commond"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    jarvis_main_gui = QtWidgets.QWidget()
    ui = Ui_jarvis_main_gui()
    ui.setupUi(jarvis_main_gui)
    jarvis_main_gui.show()
    sys.exit(app.exec_())
